### ISSUE TITLE
How to set languages?

### ISSUE THREAD

**Issue by politicus** [Skoda091/alfred-deepl#1]
Hi,

How can I modify the language the query is translated to? I want to set it to French.
How can I modify the language of the query I want to translate? I want to set it to English.

Thank you.

**Comment by Skoda091** [comment]
Hi @politicus 

I am currently working to provide multiple target languages support from Alfred input. If you want you can easily change this in the code in this [line](https://github.com/Skoda091/alfred-deepl/blob/9e053884a227ea907f591c58273efc40fe7b5882/translate.py#L54) to use with your preferred target language until I will provide this functionality 😄

**Comment by politicus** [comment]
Thank you. I had to modify the line 42 too to be able to translate from En to Fr.

Keep up the good work!

**Comment by Skoda091** [comment]
Changing translation target language added in latest release [v1.0.0](https://github.com/Skoda091/alfred-deepl/releases/tag/1.0.0).

**Comment by politicus** [comment]
@Skoda091 Sorry for the late reply. Looks like it takes both of us a month to reply ;-) I just installed the latest version and it is working very well. Thank you!
